.define kPad16_Start      #$1000
.define kPad16_Up         #$0800
.define kPad16_Down       #$0400
.define kPad16_Left       #$0200
.define kPad16_Right      #$0100
.define kPad16_TrgB       #$8000
.define kPad16_TrgA       #$0080
.define kPad16_TrgX       #$0040

.define kPad16_DirKeys    #$0F00
.define kPad16_LeftRight  #$0300
.define kPad16_A_and_St   #$1080

.define kPad_Invalidate_Mask  #$83C0

